# Generated by Django 4.2.23 on 2025-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
