# Generated by Django 4.2.23 on 2025-08-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_is_read_notification_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('spot_available', 'Spot Available'), ('booking_reminder', 'Booking Reminder'), ('booking_created', 'Booking Created'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.DeleteModel(
            name='EmailPreference',
        ),
    ]
