# Generated by Django 4.2.23 on 2025-08-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type_delete_emailpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
