# Generated by Django 5.2.5 on 2025-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingfacility_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingfacility',
            name='capacity',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
