# Generated by Django 4.2.23 on 2025-08-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingfacility_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
