# Generated by Django 4.2.23 on 2025-08-20 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0003_parkingspot_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingfacility',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='parkingfacility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SpotPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='parking.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
