# Generated by Django 5.2.5 on 2025-08-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingfacility_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auc_score', models.FloatField()),
                ('brier_score', models.FloatField()),
                ('tolerance_seconds', models.IntegerField(default=120)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingfacility',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingfacility',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
