# Generated by Django 4.2.23 on 2025-08-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_parkingfacility_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotpredictionlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
