# Generated by Django 4.2.23 on 2025-08-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_unify_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingfacility',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
