# Generated by Django 4.2.23 on 2025-08-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_parkingfacility_is_archived_parkingspot_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='external_id',
            field=models.CharField(blank=True, help_text='External OSM ID (osm-123456). Null if provider-created.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='source',
            field=models.CharField(choices=[('db', 'Database'), ('osm', 'OpenStreetMap')], default='db', max_length=20),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['latitude', 'longitude'], name='parking_par_latitud_29d856_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['external_id'], name='parking_par_externa_ebe19a_idx'),
        ),
    ]
