# Generated by Django 4.2.23 on 2025-08-26 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0008_parkingspot_external_id_parkingspot_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
