# Generated by Django 4.2.23 on 2025-08-26 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0009_alter_parkingspot_created_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parkingspot',
            name='parking_par_is_avai_794a5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingspot',
            name='parking_par_latitud_29d856_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingspot',
            name='parking_par_externa_ebe19a_idx',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
