# Generated by Django 4.2.23 on 2025-08-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_remove_parkingspot_parking_par_is_avai_794a5d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['is_available'], name='parking_par_is_avai_794a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['latitude', 'longitude'], name='parking_par_latitud_29d856_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['external_id'], name='parking_par_externa_ebe19a_idx'),
        ),
    ]
