name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image for ${{ matrix.service }}
        run: |
          docker build ./{{ matrix.service }} \
            --file ./{{ matrix.service }}/Dockerfile \
            --tag my-image-name-${{ matrix.service }}:$(date +%s)
